### ISSUE TITLE
支持大佬

### ISSUE THREAD

**Issue by k2o333** [Jiabinone/SambaNova2API#1]
从notdiamond项目找到大佬。

我自己用了litellm很重的解决了这个问题，不过项目还是很不错的。

大佬加油！！

顺便问个问题，sambanova、groq、cerebras每次请求token数有限有没有办法解决？我现在用大佬的notdiamond api貌似没啥限制。但毕竟怕哪天不能用了

**Comment by Jiabinone** [comment]
> 顺便问个问题，sambanova、groq、cerebras每次请求token数有限有没有办法解决？

不清楚
